### ISSUE TITLE
[BUG]: Every new merged tab creates a new group instead of going to the default group

### ISSUE THREAD

**Issue by REIS0** [lbragile/TabMerger#26]
**Describe the bug**
As the title says, if you merge a new tab it creates a new group,

**To Reproduce**

1. Go to any tab
2. Select to merge only this tab
3. Open tab merger menu
4. The tab creates a new group

**Expected behavior**
The tab goes to the 'default' group instead of creating a new one.

**Screenshots**
Two tabs, two new groups, as you can see in the timestamp they've been merged within seconds of difference.
![image](https://user-images.githubusercontent.com/38042161/107407159-3dbf0400-6b01-11eb-8c5a-da516ed0a2bc.png)

How they should be when merging.
![image](https://user-images.githubusercontent.com/38042161/107407426-8d9dcb00-6b01-11eb-991e-88a0657263e7.png)

**Please include the following information:**

- OS: Pop_OS! 20.10
- Browser Firefox
- Version 1.6.1

EDIT: Mistyped enter and had to edit the whole text.

**Comment by lbragile** [comment]
@REIS0 in the latest version (v1.6.1), what you described is expected behavior. Note that this should only be happening when you merge using the context menu. The reasoning is that you don't want to mix and match tabs in the top group with other tabs you are merging using the context menu, as it is impossible to tell which group the merge was intended for (unlike clicking the merge buttons inside a group). This allows the user to then simply drag and drop as needed.

Note that you could also simply use the new URL address lock icon drag and drop feature for single tab merging.

Please let me know if there is a specific spot in the documentation that needs to be updated.

**Comment by REIS0** [comment]
@lbragile thanks for the clarification, I've been using it for some time now and though the behavior hasn't changed, in this case is more of my own mistake, I'll be closing this one then.

**Comment by lbragile** [comment]
@REIS0 absolutely no problem, better be safe than sorry right? Thank you for the support.

I will double check the [documentation](https://lbragile.github.io/TabMerger-Extension/instructions) to ensure that everything there is up to date.
